# Disclaimer: with the following config, we assume that the External Secrets Operator is installed in the cluster
# We're using IAM Roles for Service Accounts (IRSA) to authenticate the SecretStore CRD with AWS Secrets Manager
#
# Assume following structure of secrets in AWS Secrets Manager
#####
### Name: redis-access-tidio-app
### Properties:
###   password : redis1234
#####
---
apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: redis-access-app-tidio
  namespace: {{ .Values.general.namespace }}
spec:
  secretStoreRef:
    name: tidio-app
    kind: SecretStore
  target:
    name: redis-access-app-tidio
  data:
    - secretKey: REDIS_PASSWORD
      remoteRef:
        key: redis-access-tidio-app
        property: password