apiVersion: v1
kind: ServiceAccount
metadata:
  annotations:
    # Use IRSA in order to grant proper permissions on AWS Secrets Manager
    eks.amazonaws.com/role-arn: arn:aws:iam::123456789012:role/aws-role-for-accessing-aws-sm
  name: {{ .Values.serviceAccounts.secretStoreServiceAccount }}
  namespace: {{ .Values.general.namespace }}
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ .Values.serviceAccounts.phpAppServiceAccount }}
  namespace: {{ .Values.general.namespace }}
---
