apiVersion: v1
kind: Service
metadata:
  labels:
    {{- include "app-subchart.labels" . | nindent 4 }}
  name: app-php-tidio
  namespace: {{ .Values.general.namespace }}
spec:
  ports:
  - port: 80
    # Default for Services but added for visibility
    protocol: TCP
    targetPort: 80
  selector:
    {{- include "app-subchart.selectorLabels" . | nindent 4 }}
  type: ClusterIP
