apiVersion: v1
kind: ServiceAccount
metadata:
  annotations:
    # Use IRSA in order to grant proper permissions on AWS Secrets Manager
    eks.amazonaws.com/role-arn: arn:aws:iam::123456789012:role/aws-role-for-accessing-aws-sm
  name: secretstore-tidio-app
  namespace: tidio-app
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: app-php-tidio
  namespace: tidio-app
---
